import json

notebook_path = 'd:/Pancar/KULIAH UNS/LOMBA/Satria Data 2026/BDC SatDat 2026/train_model.ipynb'

cells = []

# Sel 0: Markdown Judul
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# Big Data Challenge (BDC) Satria Data 2026\n",
        "## Notebook Klasifikasi Limbah Padat Tingkat Lanjut (Advanced Pipeline)\n",
        "\n",
        "**Strategi:**\n",
        "1. **Multi-Architecture Ensemble:** Menggabungkan Vision Transformer (DINOv2), ConvNeXt, dan EfficientNet.\n",
        "2. **Progressive High Resolution:** Menggunakan citra berukuran `288x288` piksel untuk detail visual yang lebih tajam.\n",
        "3. **5-Fold Cross Validation:** Setiap arsitektur dilatih menggunakan skema 5-fold cross validation secara independen.\n",
        "4. **Weighted Ensemble Inference:** Penggabungan prediksi probabilitas (soft voting) dari 15 model terbaik."
    ]
})

# Sel 1: Konfigurasi Inline & Deteksi Environment
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ============================================================\n",
        "# 1. KONFIGURASI & DETEKSI PATH DATASET (Kaggle & Colab)\n",
        "# ============================================================\n",
        "import os\n",
        "import sys\n",
        "from pathlib import Path\n",
        "\n",
        "def detect_environment():\n",
        "    if 'KAGGLE_KERNEL_RUN_TYPE' in os.environ:\n",
        "        return 'kaggle'\n",
        "    try:\n",
        "        import google.colab\n",
        "        return 'colab'\n",
        "    except ImportError:\n",
        "        pass\n",
        "    return 'local'\n",
        "\n",
        "ENV = detect_environment()\n",
        "print(f'Environment terdeteksi: {ENV}')\n",
        "\n",
        "if ENV == 'colab':\n",
        "    from google.colab import drive\n",
        "    drive.mount('/content/drive')\n",
        "    project_path = '/content/drive/MyDrive/BISMILLAH BDC 2026/BDC SatDat 2026'\n",
        "    if os.path.exists(project_path):\n",
        "        sys.path.append(project_path)\n",
        "        os.chdir(project_path)\n",
        "        print(f'Berhasil berpindah ke direktori project: {os.getcwd()}')\n",
        "\n",
        "# Setup Path Dataset\n",
        "if ENV == 'colab':\n",
        "    if Path('/content/BDC2026/train').exists():\n",
        "        DATA_DIR = Path('/content/BDC2026')\n",
        "    elif Path('/content/drive/MyDrive/BISMILLAH BDC 2026/BDC2026/train').exists():\n",
        "        DATA_DIR = Path('/content/drive/MyDrive/BISMILLAH BDC 2026/BDC2026')\n",
        "    else:\n",
        "        DATA_DIR = Path('/content/drive/MyDrive/BISMILLAH BDC 2026/BDC SatDat 2026/BDC2026')\n",
        "elif ENV == 'kaggle':\n",
        "    kaggle_input = Path('/kaggle/input')\n",
        "    found = False\n",
        "    for root, dirs, files in os.walk(kaggle_input):\n",
        "        if 'train' in dirs:\n",
        "            train_candidate = Path(root) / 'train'\n",
        "            sub_items = os.listdir(train_candidate)\n",
        "            if any('ecyclable' in s or 'lectronic' in s or 'rganic' in s for s in sub_items):\n",
        "                DATA_DIR = Path(root)\n",
        "                found = True\n",
        "                break\n",
        "    if not found:\n",
        "        DATA_DIR = kaggle_input / 'bdc2026-dataset'\n",
        "        print('WARNING: Folder train tidak ditemukan.')\n",
        "else:\n",
        "    DATA_DIR = Path('BDC2026')\n",
        "    if not DATA_DIR.exists():\n",
        "        DATA_DIR = Path('../BDC2026')\n",
        "\n",
        "TRAIN_DIR = DATA_DIR / 'train'\n",
        "TEST_DIR = DATA_DIR / 'test'\n",
        "SUBMISSION_TEMPLATE = DATA_DIR / 'submission.csv'\n",
        "\n",
        "# Setup Path Output Kerja\n",
        "if ENV == 'kaggle':\n",
        "    PROJECT_ROOT = Path('/kaggle/working')\n",
        "elif ENV == 'colab':\n",
        "    PROJECT_ROOT = Path('/content/drive/MyDrive/BISMILLAH BDC 2026/BDC SatDat 2026')\n",
        "else:\n",
        "    PROJECT_ROOT = Path('.')\n",
        "\n",
        "OUTPUTS_DIR = PROJECT_ROOT / 'outputs'\n",
        "PLOTS_DIR = OUTPUTS_DIR / 'plots'\n",
        "MODELS_DIR = PROJECT_ROOT / 'models'\n",
        "\n",
        "for d in (OUTPUTS_DIR, PLOTS_DIR, MODELS_DIR):\n",
        "    d.mkdir(parents=True, exist_ok=True)\n",
        "\n",
        "CLASS_NAMES = ['Recyclable', 'Electronic', 'Organic']\n",
        "CLASS_TO_IDX = {'Recyclable': 0, 'Electronic': 1, 'Organic': 2}\n",
        "IDX_TO_CLASS = {v: k for k, v in CLASS_TO_IDX.items()}\n",
        "IMAGENET_MEAN = (0.485, 0.456, 0.406)\n",
        "IMAGENET_STD = (0.229, 0.224, 0.225)\n",
        "SEED = 42\n",
        "\n",
        "print(f'Data dir         : {DATA_DIR} (exists={DATA_DIR.exists()})')\n",
        "print(f'Train dir        : {TRAIN_DIR} (exists={TRAIN_DIR.exists()})')\n",
        "print(f'Test dir         : {TEST_DIR} (exists={TEST_DIR.exists()})')\n",
        "print(f'Submission tmpl  : {SUBMISSION_TEMPLATE} (exists={SUBMISSION_TEMPLATE.exists()})')\n",
        "print(f'Models dir       : {MODELS_DIR}')"
    ]
})

# Sel 2: Install Library
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# 2. INSTALL LIBRARY\n",
        "!pip install -q timm scikit-learn pandas matplotlib tqdm pillow"
    ]
})

# Sel 3: Import Library & Setup Seed
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# 3. IMPORT LIBRARIES\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.optim as optim\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "from torchvision import transforms\n",
        "from PIL import Image\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import glob\n",
        "import time\n",
        "import copy\n",
        "from sklearn.model_selection import StratifiedKFold\n",
        "from sklearn.metrics import f1_score, classification_report\n",
        "from tqdm.auto import tqdm\n",
        "import matplotlib.pyplot as plt\n",
        "import timm\n",
        "\n",
        "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
        "print(f'Device: {device}')\n",
        "\n",
        "torch.manual_seed(SEED)\n",
        "np.random.seed(SEED)\n",
        "if torch.cuda.is_available():\n",
        "    torch.cuda.manual_seed_all(SEED)"
    ]
})

# Sel 4: Pengumpulan Data Latih Bersih
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# 4. PENGUMPULAN DATA LATIH\n",
        "image_paths = []\n",
        "labels = []\n",
        "\n",
        "for subfolder in os.listdir(TRAIN_DIR):\n",
        "    subfolder_path = TRAIN_DIR / subfolder\n",
        "    if os.path.isdir(subfolder_path):\n",
        "        class_idx = -1\n",
        "        name_clean = subfolder.lower()\n",
        "        if 'recyclable' in name_clean:\n",
        "            class_idx = 0\n",
        "        elif 'electronic' in name_clean:\n",
        "            class_idx = 1\n",
        "        elif 'organic' in name_clean:\n",
        "            class_idx = 2\n",
        "            \n",
        "        if class_idx != -1:\n",
        "            subfolder_images = []\n",
        "            for ext in ('*.jpg', '*.jpeg', '*.png', '*.JPG', '*.JPEG', '*.PNG'):\n",
        "                subfolder_images.extend(glob.glob(os.path.join(subfolder_path, ext)))\n",
        "            \n",
        "            unique_subfolder_images = sorted(list(set(os.path.abspath(p) for p in subfolder_images)))\n",
        "            \n",
        "            for img_path in unique_subfolder_images:\n",
        "                filename = os.path.basename(img_path)\n",
        "                if filename.startswith('.'):\n",
        "                    continue\n",
        "                image_paths.append(img_path)\n",
        "                labels.append(class_idx)\n",
        "\n",
        "df_train = pd.DataFrame({\n",
        "    'image_path': image_paths,\n",
        "    'label': labels\n",
        "})\n",
        "\n",
        "print(f'Total data latih: {len(df_train)} gambar')\n",
        "print(df_train['label'].value_counts().rename(index=IDX_TO_CLASS))"
    ]
})

# Sel 5: Dataset Class
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# 5. DATASET CLASS\n",
        "class WasteDataset(Dataset):\n",
        "    def __init__(self, dataframe, transform=None):\n",
        "        self.dataframe = dataframe.reset_index(drop=True)\n",
        "        self.transform = transform\n",
        "        \n",
        "    def __len__(self):\n",
        "        return len(self.dataframe)\n",
        "    \n",
        "    def __getitem__(self, idx):\n",
        "        row = self.dataframe.iloc[idx]\n",
        "        image = Image.open(row['image_path']).convert('RGB')\n",
        "        label = row['label']\n",
        "        if self.transform:\n",
        "            image = self.transform(image)\n",
        "        return image, label"
    ]
})

# Sel 6: Augmentasi Citra dengan Resolusi Lebih Tinggi (288x288)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# 6. AUGMENTASI (Peningkatan Resolusi ke 288x288 untuk Detail Sirkuit Elektronik/Plastik)\n",
        "IMG_SIZE = 288\n",
        "BATCH_SIZE = 32\n",
        "\n",
        "train_transforms = transforms.Compose([\n",
        "    transforms.Resize((IMG_SIZE, IMG_SIZE)),\n",
        "    transforms.RandomHorizontalFlip(p=0.5),\n",
        "    transforms.RandomVerticalFlip(p=0.2),\n",
        "    transforms.RandomRotation(15),\n",
        "    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),\n",
        "    transforms.ToTensor(),\n",
        "    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),\n",
        "])\n",
        "\n",
        "val_transforms = transforms.Compose([\n",
        "    transforms.Resize((IMG_SIZE, IMG_SIZE)),\n",
        "    transforms.ToTensor(),\n",
        "    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),\n",
        "])\n",
        "\n",
        "print(f'Image size: {IMG_SIZE} | Batch size: {BATCH_SIZE}')"
    ]
})

# Sel 7: Fungsi Epoch & Validasi
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# 7. FUNGSI TRAINING ONE EPOCH & VALIDATE\n",
        "def train_one_epoch(model, dataloader, criterion, optimizer, device):\n",
        "    model.train()\n",
        "    running_loss = 0.0\n",
        "    all_preds = []\n",
        "    all_labels = []\n",
        "    \n",
        "    for images, labels in tqdm(dataloader, desc='Training', leave=False):\n",
        "        images, labels = images.to(device), labels.to(device)\n",
        "        optimizer.zero_grad()\n",
        "        outputs = model(images)\n",
        "        loss = criterion(outputs, labels)\n",
        "        loss.backward()\n",
        "        optimizer.step()\n",
        "        \n",
        "        running_loss += loss.item() * images.size(0)\n",
        "        _, preds = torch.max(outputs, 1)\n",
        "        all_preds.extend(preds.cpu().numpy())\n",
        "        all_labels.extend(labels.cpu().numpy())\n",
        "        \n",
        "    epoch_loss = running_loss / len(dataloader.dataset)\n",
        "    epoch_f1 = f1_score(all_labels, all_preds, average='macro')\n",
        "    return epoch_loss, epoch_f1\n",
        "\n",
        "def validate(model, dataloader, criterion, device):\n",
        "    model.eval()\n",
        "    running_loss = 0.0\n",
        "    all_preds = []\n",
        "    all_labels = []\n",
        "    \n",
        "    with torch.no_grad():\n",
        "        for images, labels in tqdm(dataloader, desc='Validation', leave=False):\n",
        "            images, labels = images.to(device), labels.to(device)\n",
        "            outputs = model(images)\n",
        "            loss = criterion(outputs, labels)\n",
        "            \n",
        "            running_loss += loss.item() * images.size(0)\n",
        "            _, preds = torch.max(outputs, 1)\n",
        "            all_preds.extend(preds.cpu().numpy())\n",
        "            all_labels.extend(labels.cpu().numpy())\n",
        "            \n",
        "    val_loss = running_loss / len(dataloader.dataset)\n",
        "    val_f1 = f1_score(all_labels, all_preds, average='macro')\n",
        "    return val_loss, val_f1, all_preds, all_labels"
    ]
})

# Sel 8: Definisi Helper untuk Training Setiap Model
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# 8. HELPER FUNCTION UNTUK TRAIN K-FOLD ARSITEKTUR APA PUN\n",
        "def train_model_kfold(model_name, n_splits=5, num_epochs=6):\n",
        "    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=SEED)\n",
        "    fold_results = []\n",
        "    \n",
        "    log_file_path = PROJECT_ROOT / f'training_log_{model_name}.txt'\n",
        "    with open(log_file_path, 'w') as f:\n",
        "        f.write(f'=== LOG TRAINING {model_name} ===\\n\\n')\n",
        "        \n",
        "    def write_log(message):\n",
        "        print(message)\n",
        "        with open(log_file_path, 'a') as f:\n",
        "            f.write(message + '\\n')\n",
        "            \n",
        "    write_log(f'Memulai training {model_name} ({n_splits}-Fold)...\\n')\n",
        "    \n",
        "    for fold, (train_idx, val_idx) in enumerate(skf.split(df_train, df_train['label'])):\n",
        "        write_log('=' * 50)\n",
        "        write_log(f' {model_name} | FOLD {fold + 1} / {n_splits}')\n",
        "        write_log('=' * 50)\n",
        "        \n",
        "        fold_train_df = df_train.iloc[train_idx]\n",
        "        fold_val_df = df_train.iloc[val_idx]\n",
        "        \n",
        "        fold_train_dataset = WasteDataset(fold_train_df, transform=train_transforms)\n",
        "        fold_val_dataset = WasteDataset(fold_val_df, transform=val_transforms)\n",
        "        \n",
        "        train_loader = DataLoader(fold_train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0, pin_memory=True)\n",
        "        val_loader = DataLoader(fold_val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0, pin_memory=True)\n",
        "        \n",
        "        # Inisialisasi model dari timm\n",
        "        model = timm.create_model(model_name, pretrained=True, num_classes=len(CLASS_NAMES))\n",
        "        model = model.to(device)\n",
        "        \n",
        "        # Weighted CrossEntropy untuk menangani class imbalance (karena Electronic sedikit)\n",
        "        # Recyclable: 9999, Electronic: 3961, Organic: 12567\n",
        "        class_weights = torch.tensor([1.25, 3.17, 1.00]).to(device)  # Bobot proporsional terbalik\n",
        "        criterion = nn.CrossEntropyLoss(weight=class_weights, label_smoothing=0.1)\n",
        "        \n",
        "        optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-2)\n",
        "        scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=num_epochs)\n",
        "        \n",
        "        best_val_f1 = 0.0\n",
        "        best_model_path = MODELS_DIR / f'best_{model_name}_fold_{fold}.pth'\n",
        "        \n",
        "        for epoch in range(num_epochs):\n",
        "            start_time = time.time()\n",
        "            train_loss, train_f1 = train_one_epoch(model, train_loader, criterion, optimizer, device)\n",
        "            val_loss, val_f1, _, _ = validate(model, val_loader, criterion, device)\n",
        "            \n",
        "            scheduler.step()\n",
        "            elapsed = time.time() - start_time\n",
        "            \n",
        "            msg = (f'Epoch {epoch+1}/{num_epochs} | '\n",
        "                   f'Train Loss: {train_loss:.4f} - Train F1: {train_f1:.4f} | '\n",
        "                   f'Val Loss: {val_loss:.4f} - Val F1: {val_f1:.4f} | '\n",
        "                   f'Time: {elapsed:.2f}s')\n",
        "            write_log(msg)\n",
        "            \n",
        "            if val_f1 > best_val_f1:\n",
        "                best_val_f1 = val_f1\n",
        "                torch.save(model.state_dict(), best_model_path)\n",
        "                write_log(f'  ==> Saved best fold weights dengan Val F1: {best_val_f1:.4f}')\n",
        "                \n",
        "        fold_results.append(best_val_f1)\n",
        "        write_log(f'\\nFold {fold+1} selesai. Best Val Macro F1: {best_val_f1:.4f}\\n')\n",
        "        \n",
        "    write_log('=' * 50)\n",
        "    write_log(f' TRAINING {model_name} K-FOLD SELESAI')\n",
        "    write_log('=' * 50)\n",
        "    write_log(f'Rata-rata Macro F1-Score: {np.mean(fold_results):.4f} (+/- {np.std(fold_results):.4f})\\n')\n",
        "    return fold_results"
    ]
})

# Sel 9: Proses Training 3 Arsitektur Secara Bergantian
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# 9. EKSEKUSI MULTI-ARCHITECTURE TRAINING (DINOv2, ConvNeXt, EfficientNet)\n",
        "N_SPLITS = 5\n",
        "EPOCHS = 6\n",
        "\n",
        "# Arsitektur 1: Meta DINOv2 (Vision Transformer paling sakti)\n",
        "dinov2_results = train_model_kfold('vit_base_patch14_reg4_dinov2.lvd142m', n_splits=N_SPLITS, num_epochs=EPOCHS)\n",
        "\n",
        "# Arsitektur 2: ConvNeXt Tiny (Modern CNN)\n",
        "convnext_results = train_model_kfold('convnext_tiny', n_splits=N_SPLITS, num_epochs=EPOCHS)\n",
        "\n",
        "# Arsitektur 3: EfficientNet B2 (CNN Efisien)\n",
        "effnet_results = train_model_kfold('efficientnet_b2', n_splits=N_SPLITS, num_epochs=EPOCHS)"
    ]
})

# Sel 10: Ensemble Inference & Export CSV (ID format string fixed)
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# 10. ENSEMBLE INFERENCE (15 MODEL) & EXPORT SUBMISSION\n",
        "model_names = [\n",
        "    'vit_base_patch14_reg4_dinov2.lvd142m',\n",
        "    'convnext_tiny',\n",
        "    'efficientnet_b2'\n",
        "]\n",
        "\n",
        "print(\"Memuat 15 model terbaik untuk ensemble...\")\n",
        "models = []\n",
        "for name in model_names:\n",
        "    for fold in range(N_SPLITS):\n",
        "        model_instance = timm.create_model(name, pretrained=False, num_classes=len(CLASS_NAMES))\n",
        "        weights_path = MODELS_DIR / f'best_{name}_fold_{fold}.pth'\n",
        "        if weights_path.exists():\n",
        "            model_instance.load_state_dict(torch.load(weights_path, map_location=device))\n",
        "            model_instance = model_instance.to(device)\n",
        "            model_instance.eval()\n",
        "            models.append(model_instance)\n",
        "            print(f\"-> Loaded best_{name}_fold_{fold}.pth\")\n",
        "\n",
        "print(f\"Total model sukses termuat: {len(models)} model.\")\n",
        "\n",
        "# Koreksi ID String murni (mencegah desimal .0)\n",
        "df_submission = pd.read_csv(SUBMISSION_TEMPLATE)\n",
        "df_submission['id'] = df_submission['id'].astype(float).astype(int).astype(str)\n",
        "\n",
        "ensemble_predictions = []\n",
        "softmax = nn.Softmax(dim=1)\n",
        "\n",
        "with torch.no_grad():\n",
        "    for idx, row in tqdm(df_submission.iterrows(), total=len(df_submission), desc='Ensemble Predicting'):\n",
        "        test_id = row['id']\n",
        "        img_name_candidates = [f'{test_id}.jpg', f'{test_id}.jpeg', f'{test_id}.png']\n",
        "        img_path = None\n",
        "        for cand in img_name_candidates:\n",
        "            cand_path = TEST_DIR / cand\n",
        "            if cand_path.exists():\n",
        "                img_path = cand_path\n",
        "                break\n",
        "        \n",
        "        if img_path is None:\n",
        "            print(f'WARNING: Image dengan ID {test_id} tidak ditemukan.')\n",
        "            ensemble_predictions.append(0)\n",
        "            continue\n",
        "            \n",
        "        image = Image.open(img_path).convert('RGB')\n",
        "        image = val_transforms(image).unsqueeze(0).to(device)\n",
        "        \n",
        "        # Akumulasikan prediksi probabilitas (Soft Voting)\n",
        "        accumulated_prob = torch.zeros(1, len(CLASS_NAMES)).to(device)\n",
        "        for model_instance in models:\n",
        "            outputs = model_instance(image)\n",
        "            probs = softmax(outputs)\n",
        "            accumulated_prob += probs\n",
        "            \n",
        "        final_pred = torch.argmax(accumulated_prob, dim=1).item()\n",
        "        ensemble_predictions.append(final_pred)\n",
        "\n",
        "df_submission['predicted'] = ensemble_predictions\n",
        "output_file = PROJECT_ROOT / 'submission_SD2026040000187.csv'\n",
        "df_submission.to_csv(output_file, index=False)\n",
        "\n",
        "print(f'\\nEnsemble Master Submission sukses disimpan di: {output_file}')\n",
        "print(df_submission['predicted'].value_counts().rename(index=IDX_TO_CLASS))"
    ]
})

notebook = {
    "nbformat": 4,
    "nbformat_minor": 4,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        }
    },
    "cells": cells
}

with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print("Notebook Advanced Master Ensemble berhasil dibangun ulang!")
